- name: Server deployment
  hosts: all
  remote_user: root
  
  tasks:
  - include_vars:
      file: vars.yml
  - name: Install User & SSH
    include_role:
      name: arnobirchler.ssh-access
  - name: Install Tools
    include_role:
      name: arnobirchler.tools
  - name: Install Docker
    include_role:
      name: arnobirchler.docker